name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - config/**
      - Dockerfile
      - requirements.txt
      - .dockerignore
      - custom_log/**
      - .github/workflows/deploy.yml
jobs:
  build:
    name: Build Image
    runs-on: [ kubernetes ]
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build, tag, and push image to Amazon ECR STAGING
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/airflow-utx-reports-stg:latest
        if: github.ref == 'refs/heads/staging'

      - name: Build, tag, and push image to Amazon ECR Prod
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/airflow-utx-reports:latest
        if: github.ref == 'refs/heads/feature/main'

  deploy:
    needs: build
    runs-on: [ kubernetes ]
    steps:

      - name: Restart Scheduler Prod
        run: kubectl rollout restart deployment/airflow-scheduler -n airflow-utx-reports
        if: github.ref == 'refs/heads/feature/aws-migration'

      - name: Restart Scheduler Staging
        run: kubectl rollout restart deployment/airflow-scheduler -n airflow-utx-reports-stg
        if: github.ref == 'refs/heads/staging'

      - name: Restart Webserver Prod
        run: kubectl rollout restart deployment/airflow-webserver -n airflow-utx-reports
        if: github.ref == 'refs/heads/feature/main'

      - name: Restart Webserver Staging
        run: kubectl rollout restart deployment/airflow-webserver -n airflow-utx-reports-stg
        if: github.ref == 'refs/heads/staging'